models/alert.py
import uuid
from typing import Dict
from libs.mailgun import Mailgun
from models.item import Item
from models.model import Model
from dataclasses import dataclass, field


@dataclass(eq=False)
class Alert(Model):
    collection: str = field(init=False, default='alerts')
    name: str
    item_id: str
    user_email: str
    Price_limit: float
    item_url: str
    _id: str = field(default_factory=lambda: uuid.uuid4().hex)

    def __post_init__(self):
        self.item = Item.get_by_id(self.item_id)
        self.price: float = None


    def json(self)-> Dict:
        return{
            "item_id": self.item_id,
            "name": self.name,
            "Price_limit": self.Price_limit,
            "user_email": self.user_email,
            "item_url": self.item_url,
            "_id": self._id
        }

    def load_item_price(self) -> float:
        item = Item.get_by_id(self.item_id)
        for it in item:
            self.price = it.load_price()
            print(self.price)
        return self.price

    def get_item_url(self):
        item = Item.get_by_id(self.item_id)
        for it in item:
            self.item_url = it.url
        return self.item_url

    def notify_if_price_reached(self):
        if self.price < float(self.Price_limit):
            print(f"item {self.name} has reached a price lower than the price limit {self.Price_limit}, its price is {self.price}")
            Mailgun.send_mail(
                [self.user_email],
                'notification for {}'.format(self.name),
                'the price limit has been reached desired price.'
            )

views/alerts.py
from werkzeug.utils import redirect

from common.database import Database
from models.alert import Alert
from flask import Blueprint, render_template, request, url_for, session
from models.item import Item
from models.store import Store
from models.user import requires_login

alert_blueprint = Blueprint('alerts', __name__)


@alert_blueprint.route('/alerts/index')
@requires_login
def index():
    alerts = Alert.find_many_by('user_email', session['email'])
    return render_template('alerts/index.html', alerts=alerts)


@alert_blueprint.route('/alerts/new', methods=['GET', 'POST'])
@requires_login
def new_alert():
    if request.method == 'POST':
        item_name = request.form['item_name']
        item_url = request.form['item_url']
        user_email = session['email']
        price_limit = float(request.form['price_limit'])
        store = Store.get_by_url_self_made(item_url)
        print(store)
        if len(store) is 0:
            text1 = "The store doesnot exist in our database, please contact develpoers to add store."
            return render_template('alerts/new_alert.html', text=text1)
        else:
            for s in store:
                item = Item(item_url, s.tag_name, s.query)
            item.load_price()
            item.save_to_mongo()
            Alert(item_name, item._id, user_email, price_limit, item_url).save_to_mongo()
            text1 = "The alert has been saved to the database, if you want to save another item fill details and click button."
            return render_template('alerts/new_alert.html', text=text1)
    return render_template('alerts/new_alert.html')


@alert_blueprint.route('/alerts/edit/<string:alert_id>', methods=['GET', 'POST'])
@requires_login
def edit_alert(alert_id):
    alert = Alert.get_by_id(alert_id)
    if request.method == 'POST':
        for a in alert:
            if a.user_email == session['email']:
                Price_limit = request.form['price_limit']

                a.Price_limit = Price_limit
                a.get_item_url()
                print(a.item_url)
                print(a.name)
                a.update_to_mongo()
                text = "alert has been successfully edited"
                return redirect(url_for('.index', text=text))
    print(alert)
    return render_template('alerts/edit_alert.html', alert=alert)


@alert_blueprint.route('/alerts/delete/<string:alert_id>')
@requires_login
def delete_alert(alert_id):
    alert = Alert.get_by_id(alert_id)
    d = Database
    print(alert)
    for a in alert:
        if a.user_email == session['email']:
            item_id = a.item_id
            a.remove_from_mongo()
            d.remove('items', {"_id": item_id})
    alert = Alert.all()
    return render_template('alerts/index.html', alerts=alert)


# @alert_blueprint.route('alerts/item_check.html')
# @requires_login
# def check_alerts():
#     email_id = session['email']
#     alerts = Alert.find_many_by('user_email', email_id)
#
#     return render_template('alerts/check_alert.html', alerts=alerts)

templates/alerts/check_alerts.html
{% extends "base.html" %}
{% block content %}

templates/alerts/edit_alert.html
{% extends "base.html" %}

{% block content%}
<div class="container">
    <header><h2>Update Alert</h2></header>
    <section class="update_alert_form">
        {% for a in alert %}
        <form method="post">
            <div class="form-group">
                <label for="disabledTextInput">item name</label>
                <input name="item_name" id="disabledTextInput"   type="text"  class="form-control" value="{{ a.name }}" disabled/>
            </div>
            <div class="form-group">
                <label for="disabledTextInput1">item_url</label>
                <input name="item_url" id="disabledTextInput1"  type="text"  class="form-control" placeholder="{{ a.item_url }}" disabled />
            </div>

            <div >
                <label for="price_limit">price limit</label>
                <input name="price_limit" id="price_limit" type="text" aria-describedby="tagNameHelp" class="form-control" placeholder="{{a.Price_limit}}" />
                <small id="tagNameHelp">
                    enter the price limit of the item you want to get notified
                </small>

            </div>
            <div class="w-25 p-3" style=""></div>
            <button type="submit" class="btn btn-success">Submit</button>
        {% endfor %}
        </form>
    </section>

</div>
{% endblock %}

templates/alerts/index.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <header>
        <h2>Alerts</h2>
    </header>
        {% for alert in alerts %}
            <div class="list-group mb7">
                    <a href="{{ alert.item.url }}" class="list-group-item list-group-item-action ">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">{{ alert.name }}</h5>
                        </div>
                    </a>
                <div class="btn-group-toggle" >
                    <a class="btn btn-secondary btn-sm" href="{{ url_for('alerts.edit_alert', alert_id=alert._id) }}">
                        Edit alert
                    </a>

                    <a class="btn btn-danger btn-sm" href="{{ url_for('alerts.delete_alert', alert_id=alert._id) }}">
                        Permanently Delete
                    </a>
                    <a class="btn btn-info btn-sm" href="{{ alert.item_url }}">see item</a>

                </div>
                <div class="w-25 p-3" style=""></div>
            </div>
        {% endfor %}
        <div class="w-25 p-3" style=""></div>
        <a class="btn btn-primary" href="{{ url_for('alerts.new_alert') }}">
                Create New
        </a>
        <div class="w-25 p-3" style=""></div>
</div>
{% endblock %}

templates/alerts/new_alert.html
{% extends "base.html" %}

{% block content%}
<div class="container">
    <header><h2>Create Alert</h2></header>
    <section class="create_alert_form">
        <form method="post">
            <div class="form-group">
                <label for="item_name">item name</label>
                <input name="item_name" id="item_name" type="text"  class="form-control"/>
            </div>
            <div class="form-group">
                <label for="item_url">item_url</label>
                <input name="item_url" id="item_url" type="text"  class="form-control"/>
            </div>

            <div >
                <label for="price_limit">price limit</label>
                <input name="price_limit" id="price_limit" type="text" aria-describedby="tagNameHelp" class="form-control"/>
                <small id="tagNameHelp">
                    enter the price limit of the item you want to get notified
                </small>
            </div>
            <div class="w-25 p-3" style=""></div>
            <button type="submit" class="btn btn-success">Create</button>
            <div>
                {{ text }}
            </div>

        </form>
    </section>

</div>
{% endblock %}