models/store.py
import re
import uuid
from typing import Dict
from models.model import Model
from dataclasses import dataclass, field


@dataclass(eq=False)
class Store(Model):
    collection: str = field(init=False, default='stores')
    name: str
    url_prefix: str
    tag_name: str
    query: Dict
    _id: str = field(default_factory=lambda: uuid.uuid4().hex)

    def json(self):
        return {
            "name": self.name,
            "url_prefix": self.url_prefix,
            "tag_name": self.tag_name,
            "_id": self._id,
            "query": self.query
        }

    @classmethod
    def get_by_name(cls, store_name: str):
        return cls.find_one_by("name", store_name)

    @classmethod
    def get_by_url_prefix(cls, url_prefix: str):
        url_regex = {"$regex": "^{}".format(url_prefix)}
        return cls.find_one_by("url_prefix", url_regex)

    @classmethod
    def get_by_url_self_made(cls, url: str) -> "Store":
        a = 0
        l = len(url)
        url1 = []
        for b in range(0, l):
            if a < 3:
                if url[b] == "/":
                    a = a + 1
                url1.append(url[b])
            else:
                break
        url2 = ''.join(url1)
        data = cls.find_one_by("url_prefix", url2)
        print(data)
        return data

    @classmethod
    def convert_url(cls, url: str) -> str:
        a = 0
        l = len(url)
        url1 = []
        for b in range(0, l):
            if a < 3:
                if url[b] == "/":
                    a = a + 1
                url1.append(url[b])
            else:
                break
        url2 = ''.join(url1)
        return url2


    @classmethod
    def get_by_url(cls, url: str) -> "Store":
        pattern = re.compile(r"(https?//.*?/)")
        match = pattern.search(url)
        url_prefix = match.group(1)
        return cls.get_by_url_prefix(url_prefix)

views/storees.py
import json
from flask import Blueprint, render_template, request, url_for
from werkzeug.utils import redirect
from models.store import Store
from models.user import requires_admin, requires_login


store_blueprint = Blueprint('stores', __name__)


@store_blueprint.route('/stores')
@requires_login
def index():
    stores = Store.all()
    return render_template('stores/store_index.html', stores=stores)


@store_blueprint.route('/stores/new', methods=['Get', 'POST'])
@requires_admin
def new_store():
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['URL_Prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['HTML_Query'])
        url_prefix = Store.convert_url(url_prefix)
        store = Store(name, url_prefix, tag_name, query)
        store.save_to_mongo()
        text = "Store has been created enter the details again and press create to add another store"
        return render_template('stores/new_stores.html', text=text)
    return render_template('stores/new_stores.html')


@store_blueprint.route('/stores/edit<string:store_id>', methods=['GET', 'POST'])
@requires_admin
def edit_store(store_id):
    store = Store.get_by_id(store_id)
    print(store)
    print(store_id)
    if request.method == 'POST':
        name = request.form['name']
        #url_prefix = request.form['URL_Prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['HTML_Query'])

        for st in store:
            st.name = name
            #store.url_prefix = url_prefix
            st.tag_name = tag_name
            st.query = query
            st.update_to_mongo()
            text = "Store has been successfully edited"
            return redirect(url_for('.index', text=text, store=st))
    return render_template('stores/edit_stores.html', store=store)


@store_blueprint.route('/stores/delete<string:store_id>')
@requires_admin
def delete_store(store_id):
    store = Store.get_by_id(store_id)
    print(store_id)
    print(store)
    for a in store:
        a.remove_from_mongo()
    store = Store.all()
    return render_template('stores/store_index.html', stores=store)

templates/stores/edit_stores.html
{% extends "base.html" %}

{% block content%}
<div class="container">
    <header><h2>Edit store</h2></header>
    <section class="edit_store_form">
        {% for st in store %}
            <form method="post">
                <div class="form-group">
                    <label for="name">name</label>
                    <input name="name" id="name" type="text"  class="form-control" placeholder="{{ st.name }}" />
                </div>
                <div class="form-group">
                    <label for="URL_Prefix">URL_Prefix</label>
                    <input name="URL_Prefix" id="URL_Prefix" type="text"  class="form-control" placeholder="{{ st.URL_Prefix }} " readonly/>
                </div>
                <div >
                    <label for="tag_name">HTML Tag Name</label>
                    <input name="tag_name" id="tag_name" type="text" aria-describedby="tagNameHelp" class="form-control" placeholder="{{ st.tag_name}}"/>
                    <small id="tagNameHelp">
                        give what you want to change
                    </small>

                </div>
                <div >
                    <label for="HTML_Query">HTML_Query</label>
                    <input name="HTML_Query" id="HTML_Query" type="text" aria-describedby="tagNameHelp" class="form-control" placeholder="{{ st.query }}"/>
                    <small id="QueryHelp">
                        what change do you want in the query
                    </small>

                </div>

                <div class="w-25 p-3" style=""></div>
                    <button type="submit" class="btn btn-success">Edit</button>
                <div>
                    <label class="col-sm-2 col-form-label">{{ text }}</label>
                </div>
        {% endfor %}
        </form>
    </section>
</div>
{% endblock %}

templates/stores/new_stores.html
{% extends "base.html" %}

{% block content%}
<div class="container">
    <header><h2>Create store</h2></header>
    <section class="create_store_form">
        <form method="post">
            <div class="form-group">
                <label for="name">name</label>
                <input name="name" id="name" type="text"  class="form-control"/>
            </div>
            <div class="form-group">
                <label for="URL_Prefix">URL_Prefix</label>
                <input name="URL_Prefix" id="URL_Prefix" type="text"  class="form-control"/>
            </div>

            <div >
                <label for="tag_name">HTML Tag Name</label>
                <input name="tag_name" id="tag_name" type="text" aria-describedby="tagNameHelp" class="form-control"/>
                <small id="tagNameHelp">
                    What HTML tag contains the price info in this store?
                </small>

            </div>
            <div >
                <label for="HTML_Query">HTML_Query</label>
                <input name="HTML_Query" id="HTML_Query" type="text" aria-describedby="tagNameHelp" class="form-control"/>
                <small id="QueryHelp">
                    What HTML query contains the price in the store?
                </small>

            </div>
            <div class="w-25 p-3" style=""></div>
            <button type="submit" class="btn btn-success">Create</button>
            <div class="alert alert-light" role="alert">
                {{ text }}
            </div>

        </form>
    </section>

</div>
{% endblock %}

templates/stores/store_index.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <header>
        <h2>Stores</h2>
    </header>
    <div class="w-20 p-2" style=""></div>
        {% for store in stores %}
            <div class="list-group mb7">
                <medium>{{ store.name }}</medium>
                    <div class="container d-flex w-100 justify-content-between">
                    <small class="mb-1">for urls starting with {{ store.url_prefix }}</small>
                    </div>
                {% if session['email'] == config.ADMIN %}
                <div class="btn-group-toggle" >
                    <a class="btn btn-secondary btn-sm" href="{{ url_for('stores.edit_store', store_id=store._id) }}">
                        Edit store
                    </a>
                    <a class="btn btn-danger btn-sm" href="{{ url_for('stores.delete_store', store_id=store._id) }}">
                        Permanently Delete Store
                    </a>

                </div>
                {% endif %}
                <div class="w-25 p-3" style=""></div>
            </div>
        {% endfor %}
        <div class="w-25 p-3" style=""></div>
    {% if session['email'] == config.ADMIN %}
        <a class="btn btn-primary" href="{{ url_for('stores.new_store') }}">
                Create New
        </a>
    {% endif %}
</div>
{% endblock %}