views/alerts.py
from werkzeug.utils import redirect

from common.database import Database
from models.alert import Alert
from flask import Blueprint, render_template, request, url_for, session
from models.item import Item
from models.store import Store
from models.user import requires_login

alert_blueprint = Blueprint('alerts', __name__)


@alert_blueprint.route('/alerts/index')
@requires_login
def index():
    alerts = Alert.find_many_by('user_email', session['email'])
    return render_template('alerts/index.html', alerts=alerts)


@alert_blueprint.route('/alerts/new', methods=['GET', 'POST'])
@requires_login
def new_alert():
    if request.method == 'POST':
        item_name = request.form['item_name']
        item_url = request.form['item_url']
        user_email = session['email']
        price_limit = float(request.form['price_limit'])
        store = Store.get_by_url_self_made(item_url)
        print(store)
        if len(store) is 0:
            text1 = "The store doesnot exist in our database, please contact develpoers to add store."
            return render_template('alerts/new_alert.html', text=text1)
        else:
            for s in store:
                item = Item(item_url, s.tag_name, s.query)
            item.load_price()
            item.save_to_mongo()
            Alert(item_name, item._id, user_email, price_limit, item_url).save_to_mongo()
            text1 = "The alert has been saved to the database, if you want to save another item fill details and click button."
            return render_template('alerts/new_alert.html', text=text1)
    return render_template('alerts/new_alert.html')


@alert_blueprint.route('/alerts/edit/<string:alert_id>', methods=['GET', 'POST'])
@requires_login
def edit_alert(alert_id):
    alert = Alert.get_by_id(alert_id)
    if request.method == 'POST':
        for a in alert:
            if a.user_email == session['email']:
                Price_limit = request.form['price_limit']

                a.Price_limit = Price_limit
                a.get_item_url()
                print(a.item_url)
                print(a.name)
                a.update_to_mongo()
                text = "alert has been successfully edited"
                return redirect(url_for('.index', text=text))
    print(alert)
    return render_template('alerts/edit_alert.html', alert=alert)


@alert_blueprint.route('/alerts/delete/<string:alert_id>')
@requires_login
def delete_alert(alert_id):
    alert = Alert.get_by_id(alert_id)
    d = Database
    print(alert)
    for a in alert:
        if a.user_email == session['email']:
            item_id = a.item_id
            a.remove_from_mongo()
            d.remove('items', {"_id": item_id})
    alert = Alert.all()
    return render_template('alerts/index.html', alerts=alert)


# @alert_blueprint.route('alerts/item_check.html')
# @requires_login
# def check_alerts():
#     email_id = session['email']
#     alerts = Alert.find_many_by('user_email', email_id)
#
#     return render_template('alerts/check_alert.html', alerts=alerts)

views/storees.py
import json
from flask import Blueprint, render_template, request, url_for
from werkzeug.utils import redirect
from models.store import Store
from models.user import requires_admin, requires_login


store_blueprint = Blueprint('stores', __name__)


@store_blueprint.route('/stores')
@requires_login
def index():
    stores = Store.all()
    return render_template('stores/store_index.html', stores=stores)


@store_blueprint.route('/stores/new', methods=['Get', 'POST'])
@requires_admin
def new_store():
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['URL_Prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['HTML_Query'])
        url_prefix = Store.convert_url(url_prefix)
        store = Store(name, url_prefix, tag_name, query)
        store.save_to_mongo()
        text = "Store has been created enter the details again and press create to add another store"
        return render_template('stores/new_stores.html', text=text)
    return render_template('stores/new_stores.html')


@store_blueprint.route('/stores/edit<string:store_id>', methods=['GET', 'POST'])
@requires_admin
def edit_store(store_id):
    store = Store.get_by_id(store_id)
    print(store)
    print(store_id)
    if request.method == 'POST':
        name = request.form['name']
        #url_prefix = request.form['URL_Prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['HTML_Query'])

        for st in store:
            st.name = name
            #store.url_prefix = url_prefix
            st.tag_name = tag_name
            st.query = query
            st.update_to_mongo()
            text = "Store has been successfully edited"
            return redirect(url_for('.index', text=text, store=st))
    return render_template('stores/edit_stores.html', store=store)


@store_blueprint.route('/stores/delete<string:store_id>')
@requires_admin
def delete_store(store_id):
    store = Store.get_by_id(store_id)
    print(store_id)
    print(store)
    for a in store:
        a.remove_from_mongo()
    store = Store.all()
    return render_template('stores/store_index.html', stores=store)

views/users.py
from flask import Blueprint, session, url_for, request, render_template, redirect
from models.user import User, UserErrors


user_blueprint = Blueprint('users', __name__)


@user_blueprint.route('/users/register', methods=['POST', 'GET'])
def register_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            User.register_user(email, password)
            session['email'] = email
            return email
        except UserErrors.UserError as e:
            return e.message

    return render_template('users/register.html')


@user_blueprint.route('/users/login', methods=['POST', 'GET'])
def login_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            if User.is_login_valid(email, password):
                session['email'] = email
                text = 'welcome, {} you are now logged in'.format(email)
                return render_template('users/user_login.html', text1=text)
        except UserErrors.UserError as e:
            return e.message

    return render_template('users/user_login.html')


@user_blueprint.route('/users/logout')
def logout_user():
    session['email'] = None
    return redirect(url_for('users.login_user'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Price Alerts</title>
</head>
<body>
<div class="content container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
        <a class="navbar-brand" href="/">
            pricing service
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="@navbarNavAllMarkup" aria-controls="navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div id="navbarNavAltMarkup" class="collapse navbar-collapse">
            <a class="nav-item nav-link" href="{{ url_for('stores.index') }}">Stores</a>
            <a class="nav-item nav-link" href="{{ url_for('alerts.index') }}">Alerts</a>
            <a class="nav-item nav-link" href="{{ url_for('users.login_user') }}">Login</a>
            <a class="nav-item nav-link" href="{{ url_for('users.register_user') }}">Signup</a>
            <a class="nav-item nav-link" href="{{ url_for('users.logout_user') }}">Logout</a>
        </div>
    </nav>
</div>
<div class="content container">

        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                <div class="alert alert-{{category}}" role="alert">
                    {{ message }}
                </div>
                {% endfor %}
            {% endif%}
        {% endwith %}
    <div class="mt-3">
    {% block content %}

    {% endblock %}
    </div>
</div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Pricing Service</h1>
        <p class="lead">we scan online store websites to alert you of price drops in items that intrest you</p>
        <hr class="my-4">
        <p> just sign up and get started by addingthe URl of an item that you wish to track. We will do the rest</p>
        <a class="btn btn-primary btn-lg" href="{{ url_for('users.register_user') }}">Get stared</a>
    </div>
{% endblock %}